/**
 @Name:  CampaignMemberTriggertest
* @description: Test class for integration CampaignMember trigger. 
* 
* Change Log 
*
* Date        Author            Change Description
* -----------------------------------------------------------------------------
* 20/07/16    Rasesh Dave      Created Class  
 */
@isTest
private class CampaignMemberTriggerTest {

    static testMethod void TestCampaignMemberTrigger() {
        
        CampaignMember cm = new CampaignMember();
        
        
    }
}